### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by smola** [bblfsh/artwork#1]
Add README with a short guide on how to use artwork, hexadecimal colors to use, etc.

**Comment by mcuadros** [comment]
@marnovo

**Comment by marnovo** [comment]
Gathering some references:
https://designschool.canva.com/blog/50-meticulous-style-guides-every-startup-see-launching/
https://blog.hubspot.com/marketing/examples-brand-style-guides

We surely don't need something this extensive and fancy but they're good starting points to figure our immediate needs. So far the most pressing ones: 
- Logos usage
- Typography
- Colors

Anything else?

Can someone assign this to me please?

**Comment by marnovo** [comment]
So far…
- Logos usage:
  - Try to keep half a "fish" of distance from the logo to the other elements.
  - Try to always use in full white/light backgrounds without patterns.
- Typography:
  - Typefaces:
    - Logo typeface: `Century Gothic` (from logo)
    - Prose text typeface: `Lato` (pairs well)
    - Code text typeface: `Inconsolata` (pairs well)
  - Sizes:
    - Top Header: `24px`
    - Sub header `20px`
    - Regular text: `16px`
    - Small text: `14px`
- Colors:
  - Accent:
    - Deep orange: `#EA7024` (from logo)
    - Light orange: `#F2A62A` (from logo)
  - Base:
    - Dark grey text: `#212121`
    - Light grey text: `#B1B1B1`
    - White background: `#FFFFFF`
    - Black background: `#0b0b0b`

**Comment by marnovo** [comment]
@smola since #2 is merged I guess we can close this for now.

**Comment by dpordomingo** [comment]
@abeaumont can you close the issue?
